<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/TibcoPractice/SOAP with Attachments/Outbound/Schema.xsd" xmlns:tns="http://xmlns.example.com/1442916159083" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1442916159083">
    <types>
        <xs:schema xmlns="http://www.tibco.com/schemas/TibcoPractice/SOAP with Attachments/Outbound/Schema.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.tibco.com/schemas/TibcoPractice/SOAP with Attachments/Outbound/Schema.xsd">
            <xs:element name="partElement" type="xs:float"/>
        </xs:schema>
    </types>
    <message name="inputMsg">
        <part name="filename" type="xsd:string"/>
    </message>
    <message name="outputMsg">
        <part name="attachment" element="ns:partElement"/>
    </message>
    <portType name="PortType">
        <operation name="OutboundOperation">
            <input message="tns:inputMsg"/>
            <output message="tns:outputMsg"/>
        </operation>
    </portType>
</definitions>