<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/TibcoPractice/SOAP/Shared Variables/Schemas/Schema.xsd" xmlns:tns="http://add.sayon.com" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://add.sayon.com">
    <import namespace="http://www.tibco.com/schemas/TibcoPractice/SOAP/Shared Variables/Schemas/Schema.xsd" location="../Schemas/AddSchema.xsd"/>
    <message name="addRequest">
        <part name="addRequest" element="ns:addRequest"/>
    </message>
    <message name="addRespone">
        <part name="addResponse" element="ns:addResponse"/>
    </message>
    <portType name="AddPort">
        <operation name="add">
            <input message="tns:addRequest"/>
            <output message="tns:addRespone"/>
        </operation>
    </portType>
</definitions>